### ISSUE TITLE
OSGi (in)compatiblity

### ISSUE THREAD

**Issue by nickbreentvnz** [eiiches/jackson-jq#15]
I'm trying to use this library in an OSGi application, there are a couple of parts that don't seem to work correctly at first glance.

Generally in OSGi using the current _thread's_ context class loader does not work, the OSGi (and general multi-threaded compatible) way is to use the current _class's_ class loader.

**`net.thisptr.jackson.jq.Scope#loadConfig()`**

The context class loader cannot load the resolved "jq.json" path.

        private static List<JqJson> loadConfig() throws IOException {
                ClassLoader loader = Thread.currentThread().getContextClassLoader();
                if (loader == null)
                        loader = Scope.class.getClassLoader();
                return loadConfig(loader, resolvePath(Scope.class, "jq.json"));
       }

This class's class loader can (and always will be able to):

        private static List<JqJson> loadConfig() throws IOException {
                return loadConfig(Scope.class.getClassLoader(), resolvePath(Scope.class, "jq.json"));
        }

As an aside, using this class's class loader also removes the need for `net.thisptr.jackson.jq.Scope#resolvePath`.

**`net.thisptr.jackson.jq.Scope#loadBuiltinFunctions`**

The call to `ServiceLoader.load(Function.class)` does not  find any `net.thisptr.jackson.jq.Function` instances. 

    for (final Function fn : ServiceLoader.load(Function.class)) {

The documentation for `ServiceLoader.load(Function.class)` states: 
> Creates a new service loader for the given service type, using the _current thread's context class loader_.

Explicitly specifying this _class's_ class loader resolves this issue.

    for (final Function fn : ServiceLoader.load(Function.class, this.getClass().getClassLoader())) {

**Comment by eiiches** [comment]
Thank you for reporting this.

We can't just leave out the thread's context class loader.

In #3, we've decided to use the thread's context class loader in preference to the class's class loader.  If this doesn't work in OSGi, we probably need some means to explicitly specify from which class loader to load functions.

How about:

1. Mark no-arg `Scope()` constructor as @Deprecated.
2. Add public `loadFunctions(ClassLoader)` method which does loadMacros() and loadBuiltinsFunctions() internally with a specified class loader.
3. *Optionally* add public `loadFunctions()` which calls `loadFunctions(ClassLoader)` with a default class loader (which is the thread's context class loader if set, or the class's class loader otherwise).

This can be used like this:

```java
root = new Scope(null)
root.loadFunctions(Scope.class.getClassLoader()) // relatively heavy operation
scope = new Scope(root)
```

**Comment by nickbreentvnz** [comment]
Ah! I hadn't considered loading of custom function definitions. I've read #3 and it makes perfect sense.

In this case it's reasonable to assume that more than one class loader maybe required to load any and all function definitions.

Querying both classloaders would work too. 

1. The `Scope` Class Loader to load the standard definitions.
2. The context class loader for custom definitions.

I can put another PR together for that if you like.

**Comment by eiiches** [comment]
> In this case it's reasonable to assume that more than one class loader maybe required to load any and all function definitions.

I agree. In that case, probably we can call `loadFunctions(ClassLoader)` multiple times with the class loaders.

> Querying both classloaders would work too.

I'd rather like to take an explicit `loadFunctions(ClassLoader)` approach because similar issues can happen sometime again. As to whether `loadFunctions(/* no-arg *)` should query both class loaders not just one of them, I am not sure. I kind of prefer to re-use the current heuristic (the thread's context class loader if set or the Scope's class loader otherwise) by default.

> I can put another PR together for that if you like.

That's great! I'd appreciate it :)

**Comment by nickbreentvnz** [comment]
I've updated the PR with those changes.

I've included a couple of minor modifications to the POMs too; to support OSGi bundle JAR and wrapped the nexus plugin in a (default active) profile too. Hope those changes are acceptable.
