### ISSUE TITLE
Improved quarkus support: add jandex indexes

### ISSUE THREAD

**Issue by lburgazzoli** [eiiches/jackson-jq#194]
As follow up for https://github.com/eiiches/jackson-jq/issues/137, in order to improve the quarkus integration, it would be nice to include a [jandex](https://github.com/smallrye/jandex) index in the generated artifacts.

If this is something that can be acceptable, I can send a PR

**Comment by eiiches** [comment]
@lburgazzoli I believe the index only needs to include the classes that implement the `Function`, right? Do you think we can exclude classes from the index except:

* net.thisptr.jackson.jq.internal.filters.**
* net.thisptr.jackson.jq.internal.functions.**
* net.thisptr.jackson.jq.Function

I want to keep the index minimal so that I can be sure how the index is used outside (and ultimately to lower the chance of breaking things accidentally). This will probably also reduce the size of the index a bit.

**Comment by lburgazzoli** [comment]
I think it make sense, I will work on a PR
