### ISSUE TITLE
First try to use context classloader when resolving resources

### ISSUE THREAD

**Issue by btiernay** [eiiches/jackson-jq#3]
In general, [preference should be given to the context classloader](http://stackoverflow.com/questions/1771679/difference-between-threads-context-class-loader-and-normal-classloader). This can be done as follows:

```
  public static URL getResource(String resourceName) {
    ClassLoader loader = Objects.firstNonNull(
        Thread.currentThread().getContextClassLoader(),
        Resources.class.getClassLoader());
    URL url = loader.getResource(resourceName);
    checkArgument(url != null, "resource %s not found.", resourceName);
    return url;
  }
```

This should be done here:

https://github.com/eiiches/jackson-jq/blob/master/jackson-jq/src/main/java/net/thisptr/jackson/jq/Scope.java#L176

Otherwise things will break in certain environments (e.g. JEE, Spring Boot, etc.)

**Comment by eiiches** [comment]
@btiernay

Thanks for your suggestion.  I did some experiments with Tomcat and Spring framework, to study the actual case when this is a problem.

 1. Put jackson-jq-{version}.jar and its dependencies into $TOMCAT_HOME/lib, so that jackson-jq are loaded by a tomcat's common classloader.
 2. Put custom jq UDFs in $TOMCAT_HOME/webapps/{app}/classes/jq.json. This file can be loaded only by an application classloader.
 
In this case, using `Scope.class.getClassLoader()` did not work well. While this specific deployment is rather unrealistic, similar issues are definitely expected to happen in real circumstances.

I'm merging your PR #4. Thanks again!
