### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by kramerul** [eiiches/jackson-jq#76]
We would really like to use this excellent library. 
But it looks like it's not really maintained. 
Will vulnerabilities continue to be patched quickly in the future? 
Is this done automatically by [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/configuring-dependabot-security-updates)?

**Comment by eiiches** [comment]
I barely have time to maintain this repository right now. Still, if there's a vulnerability in one of the dependencies and if it is actually exploitable via jackson-jq, I will definitely fix it (more like I have to because I'm using jackson-jq in production). New features probably won't be implemented any time soon, though.

> Is this done automatically by Dependabot?

No, dependabot only auto-creates a PR for this repository. I have to merge the PR and release a new version manually.
