### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by yschimke** [eiiches/jackson-jq#8]
Have you considered publishing a homebrew recipe for this?

http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html

Once you have a bundle, it's pretty straightforward e.g.

https://github.com/yschimke/homebrew-tap/blob/okcurl/okcurl.rb

**Comment by eiiches** [comment]
@yschimke Do you mean a homebrew recipe for jackson-jq command?

Unfortunately I don't have Mac and not planning to publish a recipe anytime soon. If you need a bundle I will happily create one, but since jackson-jq-cli [jar](http://central.maven.org/maven2/net/thisptr/jackson-jq-cli/0.0.4/jackson-jq-cli-0.0.4.jar) includes all its dependencies so can be run as
```
java -jar jackson-jq-cli-0.0.4.jar JQ_STRING
```
and using `bin.write_jar_script` in formula like [this](https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/bfg.rb) probably works without a bundle zip (I can't confirm myself though...)

**Comment by yschimke** [comment]
Good suggestion, I'll publish one in my own repo if you don't have any objections.  Feel free to steal the recipe if you ever find this useful.

**Comment by yschimke** [comment]
Added this.  

```
$ brew install jacksonjq
==> Installing jacksonjq from yschimke/tap
==> Downloading http://central.maven.org/maven2/net/thisptr/jackson-jq-cli/0.0.4/jackson-jq-cli-0.0.4.jar
Already downloaded: /Library/Caches/Homebrew/jacksonjq-0.0.4.jar
🍺  /usr/local/Cellar/jacksonjq/0.0.4: 3 files, 3.9M, built in 0 seconds
```

**Comment by eiiches** [comment]
@yschimke Awesome! I tried this [Linuxbrew](https://github.com/Linuxbrew/linuxbrew) project and successfully installed jackson-jq cli from your repository.  Would you mind if I add a note about your tap repo in README?

**Comment by yschimke** [comment]
Sure.  Although equally, feel free to clone my repo and just keep the jacksonjq.rb recipe.  It would save coordination when you do releases.  I'm fine either way. 

BTW I hope you don't mind feature suggestions without PRs.  I need to complete a lot of paperwork before I can submit actual code, and at the moment I have other focuses.

**Comment by eiiches** [comment]
Thanks! I will clone your repo and try to keep it up to date.

And don't worry, any kind of feedback, with or without PR, is welcome.  It will help make the library more useful, robust, etc. Please let me know if there's something again :-)
